# Generated by Django 5.2.3 on 2025-06-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='conges_droit_annuel',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='conges_maladie_droit',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='conges_maladie_restants',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='conges_maladie_utilises',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='conges_planifies',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='conges_restants',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='conges_utilises',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_prochaine_evaluation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='departement',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('RH', 'RH'), ('Ventes', 'Ventes'), ('Recherche', 'Recherche'), ('Direction', 'Direction')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='eligible_prime',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='poste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='regime_sante',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium'), ('Exécutif', 'Exécutif')], default='Standard', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='responsable',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='salaire',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
